platform :ios, '9.0'

target 'douyin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'AFNetworking'
pod 'SnapKit'


  # Pods for douyin

end
